const fs = require('fs');
let code = fs.readFileSync('src/components/ModuleIngenieria.tsx', 'utf-8');

code = code.replace(
  "const handleImageFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {\n    const files = e.target.files;\n    if (files) {\n      Array.from(files).forEach((fileItem: any) => {\n        const file = fileItem as File;\n        if (file.type.startsWith('image/')) {\n          const reader = new FileReader();\n          reader.onloadend = () => {\n            if (typeof reader.result === 'string') {\n              setReferenceImages(prev => [...prev, reader.result as string]);\n              const cleanName = file.name.substring(0, file.name.lastIndexOf('.')) || file.name;\n              setReferenceImageNames(prev => [...prev, cleanName]);\n            }\n          };\n          reader.readAsDataURL(file);\n        }\n      });\n    }\n  };",
  "const handleImageFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {\n    const files = e.target.files;\n    if (files) {\n      const filesArray = Array.from(files);\n      for (let i = 0; i < filesArray.length; i++) {\n        const file = filesArray[i] as File;\n        if (file.type.startsWith('image/')) {\n          const formData = new FormData();\n          formData.append('image', file);\n          try {\n            const res = await fetch('/api/upload', {\n              method: 'POST',\n              body: formData\n            });\n            if (res.ok) {\n              const data = await res.json();\n              setReferenceImages(prev => [...prev, data.url]);\n              const cleanName = file.name.substring(0, file.name.lastIndexOf('.')) || file.name;\n              setReferenceImageNames(prev => [...prev, cleanName]);\n            }\n          } catch (e) {\n            console.error('Image upload failed', e);\n            alert('Error al subir la imagen');\n          }\n        }\n      }\n    }\n  };"
);

fs.writeFileSync('src/components/ModuleIngenieria.tsx', code);
